app:
  name: My app
  description: Welcome to ${app.name}

my:
  greeting: Hello World
  list:
  values: one, two, three

db:
  connection: "{connectionString: 'http://__', userName: 'foo', password: 'pass'}"
  host: 127.0.8.1
  port: 1200
  
  
management.endpoints.web.exposure.include: "*"

spring.profiles.active: test